### ISSUE TITLE
yarn build遇到错误

### ISSUE THREAD

**Issue by briteming** [guanpengchn/guanpengchn.github.io#81]
hi.

~/guanpengchn.github.io (dev)$ yarn build
yarn run v1.22.22
$ vue-cli-service build

|  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (C:\Users\12799\guanpengchn.github.io\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\12799\guanpengchn.github.io\node_modules\webpack\lib\NormalModule.js:401:16)
    at handleParseError (C:\Users\12799\guanpengchn.github.io\node_modules\webpack\lib\NormalModule.js:449:10)
    at C:\Users\12799\guanpengchn.github.io\node_modules\webpack\lib\NormalModule.js:481:5
    at C:\Users\12799\guanpengchn.github.io\node_modules\webpack\lib\NormalModule.js:342:12
    at C:\Users\12799\guanpengchn.github.io\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (C:\Users\12799\guanpengchn.github.io\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (C:\Users\12799\guanpengchn.github.io\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at C:\Users\12799\guanpengchn.github.io\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at runSyncOrAsync (C:\Users\12799\guanpengchn.github.io\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\12799\guanpengchn.github.io\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at Array.<anonymous> (C:\Users\12799\guanpengchn.github.io\node_modules\loader-runner\lib\LoaderRunner.js:202:4)
    at Storage.finished (C:\Users\12799\guanpengchn.github.io\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at C:\Users\12799\guanpengchn.github.io\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9
/  Building for production...Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
-  Building for production...C:\Users\12799\guanpengchn.github.io\node_modules\loader-runner\lib\LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (C:\Users\12799\guanpengchn.github.io\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\12799\guanpengchn.github.io\node_modules\webpack\lib\NormalModule.js:401:16)
    at handleParseError (C:\Users\12799\guanpengchn.github.io\node_modules\webpack\lib\NormalModule.js:449:10)
    at C:\Users\12799\guanpengchn.github.io\node_modules\webpack\lib\NormalModule.js:481:5
    at C:\Users\12799\guanpengchn.github.io\node_modules\webpack\lib\NormalModule.js:342:12
    at C:\Users\12799\guanpengchn.github.io\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (C:\Users\12799\guanpengchn.github.io\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (C:\Users\12799\guanpengchn.github.io\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at C:\Users\12799\guanpengchn.github.io\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at context.callback (C:\Users\12799\guanpengchn.github.io\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\12799\guanpengchn.github.io\node_modules\cache-loader\dist\index.js:113:16
    at C:\Users\12799\guanpengchn.github.io\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqCallback.oncomplete (node:fs:188:23) {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v23.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

如何解决？谢谢你

**Comment by sabahmax-dev** [comment]
Hi，感谢反馈～我已经开了 PR：https://github.com/guanpengchn/guanpengchn.github.io/pull/82 ，修复较新 Node.js 下 `yarn build` 报 `ERR_OSSL_EVP_UNSUPPORTED` 的构建错误，让项目能在新版 OpenSSL 环境正常打包。

**Comment by briteming** [comment]
hi.

我运行
export NODE_OPTIONS=--openssl-legacy provider && yarn build 成功生成了dist目录。并且用git命令，push了dist目录的内容到我的仓库：
https://github.com/briteming/ggi
而且我也创建了一个issue: https://github.com/briteming/ggi/issues/1
但是我访问https://briteming.github.io/ggi/ ,却什么内容也没有显示，这是怎么回事呢？

你说“通过gihtub api读取issues和各个仓库的信息”。难道是我没有设置gihtub api导致的错误吗？
该怎么设置gihtub api？
谢谢你的答复！
